language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nydyi1j52wtNbb0XxLPeRFHlSXbdn5ukvX+LKAbN6B1HDLNpc7mzfD05p2yx2fYFPwZe5VshF+7NurUstMyMZH66p3cQPoshzil7HQBRDzli9Ku2KPWLmOOw9SdT9SEdppHmD59mZjKI8v4RqjCwQg3FZBzldTceHsU/hT6Zoj9VSwDL7PhzsHr6gS7+sfVs5eqq1kTit80+Y6PkMJb3yVPkYb+bRXOZWdod1Rmir5NmMeCYcUq/F0RWxXQc1c2+Sn7DEAJS+PDQIGxWd85iY5fVYzGDIzHJ8UeqletMZlpQVqu5GaNJK9TVvffzo5m8yz1gCHVrnkiWQp8OJQi1xkejxlcgHgfZSUKMnlrhlkZGN7AvNwsIr2bAJ+RhawVD8aUngtLe4yKdC1c6cq1u9lP3PiuZA6nhjXzHRYNNr3IoxTDLxXcTKe9snITWdGF7Qf6KQ3Ql4cCtCSnrggLvB/diyPdmnw3scVChR1VtFlUIweL9kfu9Bszweed08Hkt3GGGa4WA5Ukw035LRTMRTPoWj2Ne+KY2avrFCsOyqXmjY7V6WC2EIuyhJ7DbH5mvRfOfj/ZFtHHJ9UfxDmOuQ61OcM8owvkD8ImZoMOqgzxad+eNIFkzuSvZI4gzWzJHCCzHjU2JlHy7bDWdG7QXHEBvSGdoOL5Hx5WQmrkfyeo=
  app: whats-for-dinner
  on:
    repo: patricewhite/whats-for-dinner
