language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rOhUrXsq0OJRSyxkrIYqQDEdeesuiLlV3eoPK3RFnUVQf8avPfEi4r8O2gTggbuPaQS4C/Aoe2k/LPJU38eSGUBZYttaag7+uoCi4HRqiyiNaR8sjHF3Nubs/c46uhvPlwYIQ1lBqWxS5r2GzAzilxkj149kJKIiIbrO0nsMmKKWD7IKtaamtXAhHDBrMLm0G6cNzzZNx5Yte9UrYXz3IWKcX6vG8HRl+1cDeF4yxOy2Kmy+D6CHmtioMDEW4ZNSqNvx88JiS3JQ54zIuYD4VQwxq81rDDDaCd4S+TMaYxvhoDqYA5gmFfSbMJ+hVcLIRc1csaP8EFFNvCajNLHbPXDDwtDJHPXj7wXraVBI1Qd3ysBQxKK8Ze7QvAezeDJnmdT8JWIeTMSCuUqGOiOwjqwXyCkRqdu+crV1DQvKHRrJdw6RUvLrMFvEka65P8Yvvo8WAFczowL/F1GsWKbL/L41y5ZcBakPx44W1zTRMhe2KmwUXj5Snq+ZzRthihudHesQRyxo04cPR/1DF5nfl/9roRW88C/V7lH2TGZrl6sk2TsdycGoTNC1kLyiBrkxs9JGUrMX0UquZlWKZWOrUBaobsBvDUiMOFOL2lYS2R5EbBBTDdORIov65vbyCj/SMGXtB/a35wVFbusjle/UfZVdu3IOWbBVWQOhrSt/F5o=
  app: whats-for-dinner
  on:
    repo: patricewhite/whats-for-dinner
